// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OnlineShopping.Models;


public partial class Register
{
    [Required(ErrorMessage = "pls enter username")]
    [MinLength(3, ErrorMessage = " username has to be min 3 char long")]
    public string Uname { get; set; }

    [Required(ErrorMessage = "pls enter password")]
    [MinLength(5, ErrorMessage = " username has to be min 5 char long")]
    public string Password { get; set; }

    public bool? Gender { get; set; }

    [CheckDOB(ErrorMessage = "give valid date")]
    public DateTime? Dob { get; set; }

    [Required(ErrorMessage = "pls enter designation")]
    public string Designation { get; set; }

    [Required(ErrorMessage = "pls enter email")]
    [EmailAddress(ErrorMessage = "pls enter valid email address")]
    public string Email { get; set; }
    [Required(ErrorMessage = "pls enter country field")]
    public string Country { get; set; }
}